name: 'Javadoc_evaluator'
description: 'A tool to check whether the documentation is sufficient'
author: 'Timo Schoemaker'
inputs:
  global_threshold:
    description: "The global threshold when to fail"
    required: false
branding:
  icon: 'check-circle'
  color: 'blue'
runs:
  using: 'composite'
  steps:
    - run: 'cd $GITHUB_ACTION_PATH  && npm i && npm run launch $GITHUB_WORKSPACE'
      shell: "bash"