name: 'Javadoc_evaluator'
description: 'A tool to check whether the documentation is sufficient'
author: 'Timo Schoemaker'
branding:
  icon: 'check-circle'
  color: 'blue'
runs:
  using: 'composite'
    steps:
      run: 'cd  $GITHUB_ACTION_PATH'
      run: 'tsc'
      run: 'npm run launch $GITHUB_WORKSPACE'