name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
    
      - run: npm i -g @vercel/ncc
      - run: npm run deploy && git stash && cp en-US.dic ./build/en-US.dic
        #based on https://dev.to/krzkaczor/fixing-github-actions-development-using-github-actions-33mk
        # dictionary file en-US.dic cloned from https://www.npmjs.com/package/simple-spellchecker
      - uses: ActionwareIO/branch-push-action@action
        with:
          branch: action
          files: |
            ./action.yml
            ./build/index.js
            ./build/en-US.dic
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
